# Generated by Django 4.2.3 on 2025-02-06 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('service_type', models.CharField(max_length=100)),
                ('delivery_method', models.CharField(max_length=100)),
                ('deliverables', models.TextField()),
                ('samples_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='bis_projects.client')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('client_sample_name', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=100)),
                ('extraction_quant', models.FloatField(help_text='Quantity measured during extraction')),
                ('extraction_kit', models.CharField(max_length=100)),
                ('library_quant', models.FloatField(help_text='Quantity measured during library prep')),
                ('library_kit', models.CharField(max_length=100)),
                ('targeted_depth', models.IntegerField(help_text='Targeted sequencing depth')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('projects', models.ManyToManyField(related_name='samples', to='bis_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100)),
                ('qc_status', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('samples', models.ManyToManyField(related_name='sequencing_runs', to='bis_projects.sample')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='bis_projects.clientinstitution'),
        ),
    ]
