# Generated by Django 4.2.3 on 2025-02-11 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, help_text='Enter a project ID (e.g., CP00001).', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Project ID must consist of 2–3 uppercase letters, an optional dash, 5–8 digits, and an optional dash followed by additional uppercase letters (e.g., AB01231, AB01293-AZ, AMB019203-A).', regex='^[A-Z]{2,3}-?\\d{5,8}(?:-[A-Z]+)?$')]),
        ),
    ]
