# Generated by Django 4.2.3 on 2025-02-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0002_project_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinstitution',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
