# Generated by Django 4.2.3 on 2025-02-11 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0003_remove_clientinstitution_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='bis_projects.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='bis_projects.client'),
        ),
    ]
