# Generated by Django 4.2.3 on 2025-02-11 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0005_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, help_text='Enter a project ID (e.g., CP00001).', max_length=40, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Project ID must contain only letters, digits, underscores, and dashes, must include at least one underscore, and cannot contain whitespace. Examples: 2025-01-07_8Stool_4-5W_Contract or 0101_Novozymes_49Stool_4Vag_CID.', regex='^(?=.*_)[A-Za-z0-9_-]+$')]),
        ),
    ]
