# Generated by Django 4.2.3 on 2025-02-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0006_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('LAB', 'LAB'), ('Sequencing', 'Sequencing'), ('RESEQ', 'RESEQ'), ('Complete', 'Complete'), ('FAIL', 'FAIL')], default='LAB', max_length=50),
        ),
    ]
