# Generated by Django 5.1.6 on 2025-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0009_rename_status_sample_sample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='external_run_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='run_name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='instrument',
            field=models.CharField(choices=[('Aviti', 'Aviti'), ('Nova_X', 'Nova_X'), ('MiSeq', 'MiSeq'), ('Nova_6k', 'Nova_6k'), ('ONT_GRID', 'ONT_GRID'), ('ONT_PRO', 'ONT_PRO')], max_length=8),
        ),
    ]
