# Generated by Django 5.1.6 on 2025-02-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0010_sequencingrun_external_run_id_sequencingrun_run_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(blank=True, choices=[('16s v1v3', '16s v1v3'), ('16s v3v4', '16s v3v4'), ('16s v1v8', '16s v1v8'), ('WGS', 'WGS'), ('ITS', 'ITS'), ('Isolate - SR', 'Isolate - SR'), ('Isolate - LR', 'Isolate - LR'), ('Isolate - Hyb', 'Isolate - Hyb'), ('Raw Data', 'Raw Data'), ('Kits', 'Kits'), ('Analysis Only', 'Analysis Only')], max_length=15, null=True),
        ),
    ]
