# Generated by Django 5.1.6 on 2025-02-11 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0011_alter_project_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, help_text='Enter a project ID (e.g., CP00001).', max_length=40, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Project ID must contain only letters, digits, underscores, and dashes, must include at least one underscore, and cannot contain whitespace. ', regex='^(?=.*[-_])[A-Za-z0-9_-]+$')]),
        ),
    ]
