# Generated by Django 5.1.6 on 2025-02-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0012_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='institution',
            field=models.CharField(blank=True, help_text='Enter the client institution name (e.g., Example University)', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ClientInstitution',
        ),
    ]
