# Generated by Django 5.1.6 on 2025-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0015_alter_logentry_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='barcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
