# Generated by Django 5.1.6 on 2025-02-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0016_alter_sample_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
