# Generated by Django 5.1.6 on 2025-02-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0017_sample_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(blank=True, choices=[('16S v1v3', '16S v1v3'), ('16S v3v4', '16S v3v4'), ('16S v1v8', '16S v1v8'), ('WGS', 'WGS'), ('ITS', 'ITS'), ('Isolate - SR', 'Isolate - SR'), ('Isolate - LR', 'Isolate - LR'), ('Isolate - Hyb', 'Isolate - Hyb'), ('Raw Data', 'Raw Data'), ('Kits', 'Kits'), ('Analysis Only', 'Analysis Only')], max_length=15, null=True),
        ),
    ]
