# Generated by Django 5.1.6 on 2025-02-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0018_alter_project_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='quoted_depth',
            field=models.FloatField(blank=True, help_text='Targeted sequencing depth', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='extraction_kit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='extraction_quant',
            field=models.FloatField(blank=True, help_text='Quantity measured during extraction', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_kit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_quant',
            field=models.FloatField(blank=True, help_text='Quantity measured during library prep', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='targeted_depth',
            field=models.FloatField(blank=True, help_text='Targeted sequencing depth', null=True),
        ),
    ]
