# Generated by Django 5.1.6 on 2025-02-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0019_sample_quoted_depth_alter_sample_extraction_kit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
