# Generated by Django 5.1.6 on 2025-02-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0020_client_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='sequencing_runs', to='bis_projects.sample'),
        ),
    ]
