# Generated by Django 5.1.6 on 2025-02-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_projects', '0023_alter_project_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='extraction_quant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_quant',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
